### ISSUE TITLE
TreeChop not working/buggy behavior

### ISSUE THREAD

**Issue by CalaMariGold** [hammertater/treechop#73] opened 2021-06-21 19:04 UTC
1.12.2, Forge 2855, TreeChop v0.14.1

Vanilla tree, vanilla iron axe

Tree indicator shows up but no chopping/felling. Using default configs, chopping and felling are both enabled

Mod list here: https://www.curseforge.com/minecraft/modpacks/trepidation/relations/dependencies

![2021-06-21_14 57 21](https://user-images.githubusercontent.com/57605926/122813713-44286e00-d2a1-11eb-8da4-14d3681c1634.png)
![2021-06-21_14 57 27](https://user-images.githubusercontent.com/57605926/122813721-45599b00-d2a1-11eb-8ec1-e2c5e5c64f80.png)

**Comment by hammertater** [comment] 2021-06-21 19:16
Thanks for reporting this! Could you provide me with a recent log file, such as logs/latest.log?

Also, have you tried changing any of TreeChop’s in-game settings (opened by pressing m by default)? Specifically, toggling settings like “trees must have leaves”. It would help me a lot to know if the bug seems to be related to a particular setting.

**Comment by CalaMariGold** [comment] 2021-06-21 19:33
I have tried many combinations of the options in the treechop menu. 
[latest.log](https://github.com/hammertater/treechop/files/6689040/latest.log)

**Comment by hammertater** [comment] 2021-06-21 21:03
Thanks for the log. Hm. I don't see anything in it that would explain this issue. I'll have to reproduce this myself, hopefully sometime tomorrow.

**Comment by hammertater** [comment] 2021-06-23 01:51
This should be fixed as of 0.14.4 (https://www.curseforge.com/minecraft/mc-mods/treechop/files/3361717)

**Comment by hammertater** [comment] 2021-06-23 14:48
I should add that I wasn’t able to personally test your modpack with the update; my Minecraft 1.12 installation is all messed up right now and crashes on startup for some mods. So please let me know if any issues persist.

**Closed** 2021-08-11 03:32 UTC
Labels: bug, 1.12.2

**Comment by reddvilzz** [comment] 2021-09-28 17:51
I think this has the same issue from here #81 ?

I recognize calamari as the creator of RoTN and I know RoTN uses extended days mod as well if I recall correctly. I don't know if the image attached here is from RoTN or not. But I have confirmed this happens at certain period when extended days doing it's thing and then resume after when extended days continue/unfreezes the time.

**Comment by hammertater** [comment] 2021-10-04 03:51
Extended days was causing the issue. The conflict is fixed as of 0.14.6
