### ISSUE TITLE
1.19.2 Crash on startup

### ISSUE THREAD

**Issue by rgt002** [hammertater/treechop#224] opened 2023-09-09 22:49 UTC
Getting this crash error on startup, reported to Kambrik devs, they said it looks like a HT's error. The game loaded and ran fine last time I played; tried launching the game now and I get this error. No changes were made in between.
MC 1.19.2
Fabric 0.14.22
HT's v0.18.3

![266804210-4e2dfff7-f962-4790-93bf-480a6e9ac4c1](https://github.com/hammertater/treechop/assets/69377192/f294f131-9fe4-4c3c-8675-8637d3373078)

Also, here is the console log: https://paste.atlauncher.com/view/8223bab5-574b-4245-a26e-0ea525e86ce3

**Comment by hammertater** [comment] 2023-09-10 14:30
Sorry about the crash. It’s actually even deeper! It’s caused by JobsAddon conflicting with TreeChop, see #216. You can fix the crash by downgrading to TreeChop 0.17.8a

**Comment by hammertater** [comment] 2023-12-07 01:35
The crash should be fixed per https://github.com/Globox1997/JobsAddon/issues/17. There might be other issues (see comments on that thread) but it sounds like their on JobsAddon's end.

**Closed by hammertater** 2023-12-07 01:35 UTC
