### ISSUE TITLE
[Crash] [Fabric] [1.19.2] - Client crashed on server 

### ISSUE THREAD

**Issue by SpigotDE** [hammertater/treechop#175] opened 2023-02-23 22:37 UTC
A Player on our server had a crash and it seems like cause of Tree Chop mod

[latest.log](https://gist.github.com/SpigotDE/7cc389b72f1451ec1db50bc8ef476379)

Btw 
When you break 2x2 Logs, the texture loads and while it loads you have a X-Ray sight through these logs
Could you fix this in a future update?

**Comment by ChromaPIE** [comment] 2023-02-24 04:10
Can confirm it's caused by the latest Fabric API update (0.75.0), maybe an incompat with Sodium too, not sure though.
My crash report: https://mclo.gs/nfdyIYj

**Comment by hammertater** [comment] 2023-02-24 05:47
Yeah, that's my fault, sorry about the crashes. I'll post a fix tomorrow.

**Comment by hammertater** [comment] 2023-02-25 05:41
The crash should be fixed in https://github.com/hammertater/treechop/releases/download/0.17.5/TreeChop-1.19.2-fabric-0.17.5.jar

I haven't posted to CurseForge yet, as I haven't been able to test it (due to some local installation issues...). If you try it, let me know if it works?

**Comment by CasualGeorge** [comment] 2023-02-25 18:31
Hey I had the same issue, but I just tried your new release, and it seems to work perfectly with the latest version of Fabric! :D

**Comment by hammertater** [comment] 2023-02-26 04:31
Glad to hear @CasualGeorge, thanks for letting me know :)

> When you break 2x2 Logs, the texture loads and while it loads you have a X-Ray sight through these logs
Could you fix this in a future update?

Seems to be happening when TreeChop tries to remove bark on nearby logs when Sodium is installed. They don't support some parts of the Fabric API, so I have to do some ugly stuff to get chopped logs to be drawn. To fix the x-ray issue, I've disabled the bark-removal effect when Sodium is installed.

**Comment by SpigotDE** [comment] 2023-02-26 09:53
I mostly see that when shader is applied

**Comment by hammertater** [comment] 2023-02-27 02:36
True, the flicker might appear worse on shaders for various reasons.

Both the crash and the flicker should be fixed in 0.17.6. Also, when Indium is detected, turns out I don't need to do special things for Sodium, so chopped logs should look a little better and have no x-ray issues.

Closing, but please reopen if anything still seems off.

**Closed by hammertater** 2023-02-27 02:36 UTC
Labels: bug
