### ISSUE TITLE
Using any multimedia key's causing switching chopping/felling mode

### ISSUE THREAD

**Issue by t16229a** [hammertater/treechop#27] opened 2020-12-28 15:36 UTC
I haven't assigned any multimedia key to this action in settings, even not allowed to change mode in config

**Comment by hammertater** [comment] 2020-12-28 16:23
I'd guess that minecraft doesn't like your keyboard. Could you try some things for me?
1) Open chat (press `t`) and press a few multimedia keys
2) In options > controls, bind some default control like "jump" to the `n` key (by default, or whatever key is configured to toggle chopping) and see if your multimedia keys cause you to jump?

If pressing multimedia keys for (1) types random letters into the chat box or (2) causes you to jump, then minecraft probably doesn't like your keyboard. You could try updating the keyboard's drivers/firmware if you know how, or just bind the toggleChopping control to a different key.

If not, could you send me the model number of your keyboard?

**Comment by t16229a** [comment] 2020-12-28 17:41
1. It works fine, while chat is open - multimedia keys works as intended and it doesn't affect mod
2. There is some catch. I have no any key assigned to toggle chopping mode (all 3 control keys is empty by pressing esc). Right now, while I'm using multimedia keys, i have messages "chopping ON/OFF", but if I restore default key for toggle (n) and use multimedia keys - I get "Felling ON/OFF". So, for experiment I clear jumping key by esc, and multimedia causes no jump.

Thanks for your response. I tested this issue on 2 computers with 2 different keyboards, but with same config and controls settings. It was SVEN GS-9400 (Fn+F1-F12) and A4tech GR-86 (built-in multimedia keys). How else can I help?

**Comment by hammertater** [comment] 2020-12-28 18:34
>I have no any key assigned to toggle chopping mode (all 3 control keys is empty by pressing esc)

Ahhh okay, sorry, I read your first message wrong. I just tried the same thing and saw the same bug on my setup. Minecraft seems to use a key value of -1 for both "unassigned" and keys it doesn't know, like multimedia keys, so pressing any key it doesn't know about will trigger unassigned controls. It's an easy thing to fix, so I'll post a new version soon. In the meantime, I suppose you can just bind this mod's controls to buttons you'll never use.

**Comment by t16229a** [comment] 2020-12-28 18:57
Thank you for taking time to solving this issue so promptly and explaining what it causes. Love your mod, good luck!

**Comment by hammertater** [comment] 2020-12-30 22:29
No problem at all, and thanks! The issue is fixed in version 0.11.2 at https://www.curseforge.com/minecraft/mc-mods/treechop/files/3153719. I'm gonna go ahead and close this issue now. 👍

**Closed** 2020-12-30 22:30 UTC
