### ISSUE TITLE
Client Side render crash

### ISSUE THREAD

**Issue by Poke097** [hammertater/treechop#142] opened 2022-11-08 19:35 UTC
[crash-2022-11-08_13.28.15-client.txt](https://github.com/hammertater/treechop/files/9964559/crash-2022-11-08_13.28.15-client.txt)

When going to the area with the chopped log, it crashes the game :(

**Comment by hammertater** [comment] 2022-11-09 05:19
Hey Poke, sorry about that! I'll look into this asap.

**Comment by LukeZaz** [comment] 2022-11-14 03:45
Figured I'd drop by to say I'm getting an extremely similar error on a server I'm running. I narrowed it down to happening whenever TreeChop tries to work with bamboo that has natural leaves attached, so #126 would help a lot here too.

I've attached one of my crash logs as well, but in the meantime for anyone coming here off Google, you can at least fix the block in question by doing `/setblock [position] minecraft:air` to replace the block causing the crash. You can get the position off the crash report, and if you're hosting a server but crash as soon as you log in, remember that you can run the command from the console. If it complains the position isn't loaded, then try running the command in the brief time after joining the server but before your client loads the chunks.

[crash-2022-11-13_21.09.24-client.txt](https://github.com/hammertater/treechop/files/9999291/crash-2022-11-13_21.09.24-client.txt)

**Comment by hammertater** [comment] 2022-11-14 05:55
Thanks for the info! I probably would not have figured that out. I'll prioritize #126 after dealing with this, it definitely could help in these situations.

**Comment by hammertater** [comment] 2022-11-17 01:13
I haven't been able to reproduce the crash using just sodium + treechop. @LukeZaz is there a modpack for your server that I could try?

**Comment by Poke097** [comment] 2022-11-17 01:16
https://www.curseforge.com/minecraft/modpacks/a-little-bit-of-everything-fabric

This is my modpack which I had your mod on but took off due to the issues

**Comment by hammertater** [comment] 2022-11-17 02:47
That would be great! Could you also tell me the coordinates of the area where the crash happens?

**Comment by LukeZaz** [comment] 2022-11-17 03:54
Unfortunately the modpack we're using is a custom one that we made and it's a bit too big to attach to a Github comment. I'll try and narrow down the issue a bit more based on mods and I'll report back once I know more. Shouldn't be long!

**Comment by hammertater** [comment] 2022-11-17 03:58
Hey @LukeZaz, I think I know what the issue is, so no need for now. I should be able confirm whether or not it's fixed using Poke's save files. Thanks though!

**Comment by LukeZaz** [comment] 2022-11-17 04:25
Too bad, I tested anyways! I got too curious, haha. Anyway, in the event it helps any, I found out the problem goes away once I removed William Wyther's Overhauled Overworld. Even if the world wasn't generated using it, having it enabled causes the bamboo breaking to crash the game.

**Comment by hammertater** [comment] 2022-11-17 05:14
Ha, there it is. That mod adds the "log" tag to bamboo. I was wondering which mod did that, it makes TreeChop activate on bamboo.

Since you're all sorts of curious - the root of the crash is that TreeChop uses the texture of the original log (or its stripped version) when drawing chopped logs. Bamboo blocks use a weird shape, so TreeChop fails to get the texture, and the game crashes.

**Comment by Poke097** [comment] 2022-11-17 07:22
https://drive.google.com/file/d/1L9OOMMCp-K0b-Hntu9OjJ8FGhSyntzPD/view?usp=sharing

This is the mod pack for the server only, so it only works when loading a server

**Comment by Poke097** [comment] 2022-11-17 07:24
THESE were the exact coods  (-7,64,-21)
but I didn't have an issue with bamboo so dunno
maybe because it was modded wood but it didn't look odd so I wouldn't know

**Comment by Poke097** [comment] 2022-11-17 07:24
Run the zip through virus total just in case you wanna test the legitimacy :o

**Comment by hammertater** [comment] 2022-12-08 20:23
Sorry for the wait! This should all be fixed in 0.17.0 for minecraft 1.19.2. I'll port the fix to 1.18.2 as soon as I can

**Comment by hammertater** [comment] 2023-01-31 04:10
Ported to 1.18.2, closing

**Closed by hammertater** 2023-01-31 04:10 UTC
Labels: done
