### ISSUE TITLE
Respawn NPE

### ISSUE THREAD

**Issue by WenXin20** [hammertater/treechop#37] opened 2021-01-26 04:31 UTC
`Minecraft v1.16.5`
`Forge v36.0.1`
`Tree Chop v0.12.1`
[`Exotic Birds v1.0.3`](https://www.curseforge.com/minecraft/mc-mods/exotic-birds)

I died on my server, but every time I clicked respawn, it would reappear. The server log also printed out an error every time the button was clicked. It mentions both this mod and Exotic Birds.
[Error Log](https://gist.github.com/WenXin20/ed3d1cbf08ca935b371014e9a1024638)

Also reported to https://www.curseforge.com/minecraft/mc-mods/exotic-birds/issues/63

**Comment by hammertater** [comment] 2021-01-27 02:43
Thanks for the log! I'll have the TreeChop error fixed in a day or two.

**Comment by WenXin20** [comment] 2021-01-27 02:47
Thanks!

**Comment by hammertater** [comment] 2021-01-28 04:28
0.12.2 is posted with the fix. TreeChop won't show errors anymore when trying to respawn, but the root of the problem is still there (most likely another mod is messing up player information when respawning), so Exotic Birds will still show errors until it is also updated with a similar fix.

**Comment by WenXin20** [comment] 2021-01-28 05:10
Will that fix be unable to respawn?

**Comment by hammertater** [comment] 2021-01-28 05:41
I think Exotic Birds needs to be updated to fix your respawn problem :( it’s a really bad bug!

**Comment by WenXin20** [comment] 2021-01-28 05:54
Yeah, true!

**Comment by hammertater** [comment] 2021-01-28 05:55
You could try this:
1) back up your world
2) remove Exotic Birds from your mods folder
3) start the game
4) respawn
5) quit the game
4) put Exotic Birds back into your mods folder

This might fix your respawn problem. However, if there are any birds near you, they will disappear. Also, make sure you’re using TreeChop 0.12.2.

**Comment by WenXin20** [comment] 2021-01-28 06:02
It's was just a test world anyways. :)

**Closed** 2021-10-03 21:12 UTC
