### ISSUE TITLE
Compatibility issues with "Multi Mine"

### ISSUE THREAD

**Issue by sinterde** [hammertater/treechop#285] opened 2024-07-09 05:06 UTC
"Multi Mine" has the function of maintaining the progress of excavation. When used together, the effect of 'HT's TreeChop' will disappear when cutting trees. The wood will not become thinner but will fall directly. The trees will float in the air just like the original version.

**Comment by hammertater** [comment] 2024-07-24 15:29
Thanks for reporting, and sorry for the delay. Which versions of Minecraft, TreeChop, and Multi Mine are you using?

**Comment by hammertater** [comment] 2024-07-27 05:06
See https://github.com/hammertater/treechop/issues/283#issuecomment-2253767531

> As of TreeChop 0.19.1, I got around this issue by disabling MultiMine while chopping. Only for Minecraft 1.19.2 at the moment, will port to 1.20.1 and 1.21 shortly.

Closing this issue as a duplicate of https://github.com/hammertater/treechop/issues/283

**Closed by hammertater** 2024-07-27 05:06 UTC
Labels: compatibility

**Comment by sinterde** [comment] 2024-08-10 06:00
Thank you for your work and look forward to the new version of 1.20.1.❤️
